---
config:
  kanban:
    ticketBaseUrl: 'https://github.com/TimCixo/safetensors-extra-data/issues/#TICKET#'
---
kanban
    backlog[Backlog]
    todo[Todo]
    inProgress[In Progress]
    testing[Testing]
    done[Done]
